include:
  - board: nice_nano
    shield: lily58_left
    cmake-args: -DCONFIG_ZMK_STUDIO=y -DCONFIG_ZMK_SLEEP=y -DCONFIG_ZMK_IDLE_TIMEOUT=60000
    artifact-name: ergo_s1_oe_left
    snippet: studio-rpc-usb-uart
  - board: nice_nano
    shield: ergo_s1_oe_right
    cmake-args: -DCONFIG_ZMK_SLEEP=y -DCONFIG_ZMK_IDLE_TIMEOUT=60000
    artifact-name: nice_lily58_right_oled

  # ProMicro_Dongle
  - board: nice_nano
    shield: ergo_s1_oe_dongle_pro_micro dongle_display
    cmake-args: -DCONFIG_ZMK_STUDIO=y -DCONFIG_ZMK_SLEEP=n -DCONFIG_ZMK_IDLE_TIMEOUT=60000
    artifact-name: nice_ergo_s1_oe_dongle_oled
    snippet: studio-rpc-usb-uart
